In [81]:
import requests
import pandas as pd
# Azért, hogy pd.Dataframe-nél ne csak az általa választott oszlopmennyiséget adja meg, ezért szükség van az alábbira:
pd.set_option("display.max_columns",30)
from datetime import datetime

# napok közit különbség kiszámolása
from dateutil.relativedelta import relativedelta

In [82]:
current_datetime = datetime.now() - relativedelta(months=2)

formatted_datetime = current_datetime.strftime("%Y-%m-%d")

formatted_datetime

'2025-09-20'

In [83]:
#taxi trips lekérés fix napra:

url = (
    f"https://data.cityofchicago.org/resource/ajtu-isnz.json?"
    f"$where=trip_start_timestamp >= '{formatted_datetime}T00:00:00'"
    f"AND trip_start_timestamp <= '{formatted_datetime}T23:59:59'"
    f"&$limit=30000"
)

response = requests.get(url)
data = response.json()

len(data)

18544

In [84]:
# Adatok df-esítése

taxi_trips = pd.DataFrame(data)

taxi_trips.head()

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area,dropoff_community_area,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,pickup_centroid_location,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location,pickup_census_tract,dropoff_census_tract
0,a28e656e3ccb41a818668ad308445c3f69ec29d7,1344830e881c7eba092d0c19fc0d33fb004fce69324141...,2025-09-20T23:45:00.000,2025-09-21T00:45:00.000,3407,17.65,35,77,47.75,0,0,1,48.75,Cash,Flash Cab,41.835117986,-87.618677767,"{'type': 'Point', 'coordinates': [-87.61867776...",41.9867118,-87.663416405,"{'type': 'Point', 'coordinates': [-87.66341640...",NaN,NaN
1,a70c202c230b2c3a8aa50da2867486ca20a07deb,137a3605d33badaf4f3ced9115d44ebd822c90ec3cedcb...,2025-09-20T23:45:00.000,2025-09-21T00:00:00.000,747,2.51,6,8,13.83,0,0,0,14.33,Mobile,Flash Cab,41.944226601,-87.655998182,"{'type': 'Point', 'coordinates': [-87.65599818...",41.899602111,-87.633308037,"{'type': 'Point', 'coordinates': [-87.63330803...",NaN,NaN
2,a8143c6a22103381d830b2c40783c79c5d7e91c7,449fa4909552757130d09d98ebc7770e2dd94579036b0e...,2025-09-20T23:45:00.000,2025-09-21T00:00:00.000,372,1.14,24,24,9.5,2.2,0,0,12.2,Mobile,Flash Cab,41.901206994,-87.676355989,"{'type': 'Point', 'coordinates': [-87.67635598...",41.901206994,-87.676355989,"{'type': 'Point', 'coordinates': [-87.67635598...",NaN,NaN
3,a8e2d3ce2b322e88330f0f7bb3ba14e5fe47e4a3,c3c7eca7dbd2a69ff3195e717334343ed19de792129c84...,2025-09-20T23:45:00.000,2025-09-20T23:45:00.000,504,2.16,32,8,33.5,0,0,0,34,Credit Card,Globe Taxi,41.878865584,-87.625192142,"{'type': 'Point', 'coordinates': [-87.62519214...",41.899602111,-87.633308037,"{'type': 'Point', 'coordinates': [-87.63330803...",NaN,NaN
4,ad7a23208bdfdba65c04cb69959a478cd473731d,0bea3de3c36237d68b009b24ee3db86c78e9e618a73a3b...,2025-09-20T23:45:00.000,2025-09-21T00:15:00.000,1920,14.4,56,6,37.25,0,0,10,47.25,No Charge,Transit Administrative Center Inc,41.79259236,-87.769615453,"{'type': 'Point', 'coordinates': [-87.76961545...",41.944226601,-87.655998182,"{'type': 'Point', 'coordinates': [-87.65599818...",NaN,NaN

In [85]:
# Adatok általános vizsgálata

taxi_trips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18544 entries, 0 to 18543
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   trip_id                     18544 non-null  object
 1   taxi_id                     18544 non-null  object
 2   trip_start_timestamp        18544 non-null  object
 3   trip_end_timestamp          18544 non-null  object
 4   trip_seconds                18540 non-null  object
 5   trip_miles                  18544 non-null  object
 6   pickup_community_area       18186 non-null  object
 7   dropoff_community_area      17266 non-null  object
 8   fare                        18520 non-null  object
 9   tips                        18520 non-null  object
 10  tolls                       18520 non-null  object
 11  extras                      18520 non-null  object
 12  trip_total                  18520 non-null  object
 13  payment_type                18544 non-null  object
 14  company                     18544 non-null  object
 15  pickup_centroid_latitude    18190 non-null  object
 16  pickup_centroid_longitude   18190 non-null  object
 17  pickup_centroid_location    18190 non-null  object
 18  dropoff_centroid_latitude   17313 non-null  object
 19  dropoff_centroid_longitude  17313 non-null  object
 20  dropoff_centroid_location   17313 non-null  object
 21  pickup_census_tract         7953 non-null   object
 22  dropoff_census_tract        7803 non-null   object
dtypes: object(23)
memory usage: 3.3+ MB

In [86]:
# Adatok általános vizsgálata

taxi_trips.describe()

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area,dropoff_community_area,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,pickup_centroid_location,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location,pickup_census_tract,dropoff_census_tract
count,18544,18544,18544,18544,18540,18544,18186,17266,18520,18520,18520,18520,18520,18544,18544,18190,18190,18190,17313,17313,17313,7953,7803
unique,18544,2102,96,112,3237,2301,77,77,2343,984,29,170,3156,7,30,160,160,160,165,165,165,83,91
top,a28e656e3ccb41a818668ad308445c3f69ec29d7,6ad5805a727e5aa27d3c226e4c88faa41f494b01215006...,2025-09-20T18:00:00.000,2025-09-20T18:15:00.000,0,0,8,8,9.5,0,0,0,3.25,Mobile,Flash Cab,41.899602111,-87.633308037,"{'type': 'Point', 'coordinates': [-87.63330803...",41.899602111,-87.633308037,"{'type': 'Point', 'coordinates': [-87.63330803...",17031980000,17031320100
freq,1,43,373,377,244,1568,4768,4684,530,11534,18376,13398,194,6206,3799,2031,2031,2031,1730,1730,1730,1210,721

In [87]:
#Problémás fare esetek elemzése (a cashnél van a gond)
taxi_trips[taxi_trips['fare'].isna()].sample(10)

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area,dropoff_community_area,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,pickup_centroid_location,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location,pickup_census_tract,dropoff_census_tract
16334,0e6919258c3a2f932ab62e10965a7dcbc412f2e9,fe659851fec6b2684321a52e42b1a316dd6657ba108f61...,2025-09-20T08:45:00.000,2025-09-20T08:45:00.000,116,0,76,76,NaN,NaN,NaN,NaN,NaN,Cash,City Service,41.97907082,-87.903039661,"{'type': 'Point', 'coordinates': [-87.90303966...",41.97907082,-87.903039661,"{'type': 'Point', 'coordinates': [-87.90303966...",17031980000,17031980000
7479,7ca6056f45b824d67a04a848f5af6af5af52acad,eaf9ff311ef5bc5e9f673e209710280ab0cc565517ee62...,2025-09-20T16:30:00.000,2025-09-20T16:30:00.000,51,0.07,32,32,NaN,NaN,NaN,NaN,NaN,Cash,Tac - Yellow Cab Association,41.880994471,-87.632746489,"{'type': 'Point', 'coordinates': [-87.63274648...",41.880994471,-87.632746489,"{'type': 'Point', 'coordinates': [-87.63274648...",17031839100,17031839100
15904,b3cf5c3db66c1d12a5bd264c4a4e87abec6736c1,b9a58663518c48b09e83f462ca25ee0d702a2e4bc12199...,2025-09-20T09:15:00.000,2025-09-20T09:15:00.000,241,0.61,3,3,NaN,NaN,NaN,NaN,NaN,Cash,City Service,41.96581197,-87.655878786,"{'type': 'Point', 'coordinates': [-87.65587878...",41.96581197,-87.655878786,"{'type': 'Point', 'coordinates': [-87.65587878...",NaN,NaN
13346,42fc3379bf6235d4944c38d9b5c0aa2786949762,5e61d7ef452d7ccbf325ff879ffbf59eeb89f68ec78623...,2025-09-20T12:00:00.000,2025-09-20T12:15:00.000,1459,0.2,8,8,NaN,NaN,NaN,NaN,NaN,Cash,Flash Cab,41.899602111,-87.633308037,"{'type': 'Point', 'coordinates': [-87.63330803...",41.899602111,-87.633308037,"{'type': 'Point', 'coordinates': [-87.63330803...",NaN,NaN
16075,93b5704b45c73738e456fa9a85b8aac5bd8b7f82,87a21e5ac34dbe38d564b74375f29cdcc5f88e81aa27d9...,2025-09-20T09:00:00.000,2025-09-20T09:30:00.000,1675,24.21,76,NaN,NaN,NaN,NaN,NaN,NaN,Cash,Flash Cab,41.97907082,-87.903039661,"{'type': 'Point', 'coordinates': [-87.90303966...",NaN,NaN,NaN,17031980000,NaN
2507,c606f0fd240efa804657703f3c4861426161d3d6,aa4c3beb61a579d4f214d3f92395a4f7bc7245a2cb21eb...,2025-09-20T20:30:00.000,2025-09-20T20:45:00.000,897,1.98,8,32,NaN,NaN,NaN,NaN,NaN,Cash,Sun Taxi,41.899602111,-87.633308037,"{'type': 'Point', 'coordinates': [-87.63330803...",41.878865584,-87.625192142,"{'type': 'Point', 'coordinates': [-87.62519214...",NaN,NaN
8860,fd58d6237ea2842cc28aebefa0fa6962baa566a4,c53dba6f2d4174b792e113023de74f54e5af52ba87cf1a...,2025-09-20T15:15:00.000,2025-09-20T15:15:00.000,30,0.1,32,32,NaN,NaN,NaN,NaN,NaN,Cash,5 Star Taxi,41.877406123,-87.621971652,"{'type': 'Point', 'coordinates': [-87.62197165...",41.877406123,-87.621971652,"{'type': 'Point', 'coordinates': [-87.62197165...",17031320400,17031320400
7725,ab829ce61205645fb611c2ffc886e9bef17fb879,62d8066f9c6d8b2909413e6f4729fad33c05b86a67d931...,2025-09-20T16:15:00.000,2025-09-20T16:30:00.000,1063,1.62,32,8,NaN,NaN,NaN,NaN,NaN,Cash,City Service,41.870607372,-87.622172937,"{'type': 'Point', 'coordinates': [-87.62217293...",41.89503345,-87.619710672,"{'type': 'Point', 'coordinates': [-87.61971067...",17031320600,17031081401
14478,0c6ac67a43b4b92ddd245fe68b786e53984bcd4b,64fef3c62cbbc9dd8c00e7e1cf6d29ea73d9ebdd758d4f...,2025-09-20T11:00:00.000,2025-09-20T11:15:00.000,976,3.84,28,8,NaN,NaN,NaN,NaN,NaN,Cash,5 Star Taxi,41.863118103,-87.672920435,"{'type': 'Point', 'coordinates': [-87.67292043...",41.890922026,-87.618868355,"{'type': 'Point', 'coordinates': [-87.61886835...",17031842900,17031081403
9,af85882dab76f7f63f4929fc95abb77fac943e68,6886ad17743bd14735d9bf14bda5d28d5446edaafb75e4...,2025-09-20T23:45:00.000,2025-09-20T23:45:00.000,NaN,0.01,33,33,NaN,NaN,NaN,NaN,NaN,Cash,Sun Taxi,41.859349715,-87.617358006,"{'type': 'Point', 'coordinates': [-87.61735800...",41.859349715,-87.617358006,"{'type': 'Point', 'coordinates': [-87.61735800...",17031330100,17031330100

## Adatok átalakítása

## NaN adatok elhagyása

In [88]:
taxi_trips.drop(['pickup_census_tract' , 'dropoff_census_tract'], axis=1, inplace=True)

In [89]:
# A pickup centroid latitude + longitude = pickup_centroid_location --> duplikátum --> nem kell

taxi_trips.drop(['pickup_centroid_location','dropoff_centroid_location'],axis=1,inplace=True)

In [90]:
#Az üres értékkel rendelkező sorok elhagyása

taxi_trips.dropna(inplace=True)

In [91]:
taxi_trips.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17103 entries, 0 to 18540
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   trip_id                     17103 non-null  object
 1   taxi_id                     17103 non-null  object
 2   trip_start_timestamp        17103 non-null  object
 3   trip_end_timestamp          17103 non-null  object
 4   trip_seconds                17103 non-null  object
 5   trip_miles                  17103 non-null  object
 6   pickup_community_area       17103 non-null  object
 7   dropoff_community_area      17103 non-null  object
 8   fare                        17103 non-null  object
 9   tips                        17103 non-null  object
 10  tolls                       17103 non-null  object
 11  extras                      17103 non-null  object
 12  trip_total                  17103 non-null  object
 13  payment_type                17103 non-null  object
 14  company                     17103 non-null  object
 15  pickup_centroid_latitude    17103 non-null  object
 16  pickup_centroid_longitude   17103 non-null  object
 17  dropoff_centroid_latitude   17103 non-null  object
 18  dropoff_centroid_longitude  17103 non-null  object
dtypes: object(19)
memory usage: 2.6+ MB

## Oszlopok átnevezése

In [92]:
# pickup és dropoff community area oszlopok átnevezése

taxi_trips.rename(columns={'pickup_community_area':'pickup_community_area_id',
                            'dropoff_community_area' : 'dropoff_community_area_id'}, inplace=True )

In [93]:
taxi_trips.columns

Index(['trip_id', 'taxi_id', 'trip_start_timestamp', 'trip_end_timestamp',
       'trip_seconds', 'trip_miles', 'pickup_community_area_id',
       'dropoff_community_area_id', 'fare', 'tips', 'tolls', 'extras',
       'trip_total', 'payment_type', 'company', 'pickup_centroid_latitude',
       'pickup_centroid_longitude', 'dropoff_centroid_latitude',
       'dropoff_centroid_longitude'],
      dtype='object')

## Transformation: create helper columns for weather and date dimension

In [94]:
# Taxi trips startdate adattípus objectről stringre

taxi_trips['trip_start_timestamp'] = pd.to_datetime(taxi_trips['trip_start_timestamp'])

In [95]:
taxi_trips.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17103 entries, 0 to 18540
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   trip_id                     17103 non-null  object
 1   taxi_id                     17103 non-null  object
 2   trip_start_timestamp        17103 non-null  datetime64[ns]
 3   trip_end_timestamp          17103 non-null  object
 4   trip_seconds                17103 non-null  object
 5   trip_miles                  17103 non-null  object
 6   pickup_community_area_id    17103 non-null  object
 7   dropoff_community_area_id   17103 non-null  object
 8   fare                        17103 non-null  object
 9   tips                        17103 non-null  object
 10  tolls                       17103 non-null  object
 11  extras                      17103 non-null  object
 12  trip_total                  17103 non-null  object
 13  payment_type                17103 non-null  object
 14  company                     17103 non-null  object
 15  pickup_centroid_latitude    17103 non-null  object
 16  pickup_centroid_longitude   17103 non-null  object
 17  dropoff_centroid_latitude   17103 non-null  object
 18  dropoff_centroid_longitude  17103 non-null  object
dtypes: datetime64[ns](1), object(18)
memory usage: 2.6+ MB

In [96]:
# dátumidő segédoszlop időjáráshoz --> idő lekerekítése a legközelebbi egészórára

taxi_trips['datetime_for_weather'] = taxi_trips["trip_start_timestamp"].dt.floor('h')

In [97]:
taxi_trips['datetime_for_weather']

0       2025-09-20 23:00:00
1       2025-09-20 23:00:00
2       2025-09-20 23:00:00
3       2025-09-20 23:00:00
4       2025-09-20 23:00:00
                ...
18535   2025-09-20 00:00:00
18536   2025-09-20 00:00:00
18537   2025-09-20 00:00:00
18539   2025-09-20 00:00:00
18540   2025-09-20 00:00:00
Name: datetime_for_weather, Length: 17103, dtype: datetime64[ns]

In [98]:
# Taxi trips startdate adattípus objectről stringre

taxi_trips['trip_start_date'] = pd.to_datetime(taxi_trips['trip_start_timestamp']).dt.date

In [99]:
taxi_trips['trip_start_date'].sample(5)

17275    2025-09-20
17770    2025-09-20
8850     2025-09-20
14024    2025-09-20
5498     2025-09-20
Name: trip_start_date, dtype: object

## Taxi és időjárási adatok összekötése

In [100]:
# időjárási adatok beolvasása

current_datetime = datetime.now() - relativedelta(months=2)

formatted_datetime = current_datetime.strftime("%Y-%m-%d")

url = "https://archive-api.open-meteo.com/v1/era5"


# Az URL-beli értékek cseréje dictionary-vel:

params = {
    "latitude": 41.85,
    "longitude": -87.65,
    "start_date": formatted_datetime,
    "end_date": formatted_datetime,
    "hourly" : "temperature_2m,wind_speed_10m,rain,precipitation"
}

response = requests.get(url , params=params)
data = response.json()

weather_data = {
    "datetime" : data["hourly"]["time"],
    "temperature" : data["hourly"]["temperature_2m"],
    "wind_speed" : data["hourly"]["wind_speed_10m"],
    "rain" : data["hourly"]["rain"],
    "precipitation" : data["hourly"]["precipitation"]
}

#Mivel objectnek fordítja alapból a dátumot, ez át kell alakítani

weather_df = pd.DataFrame(weather_data)

weather_df["datetime"] = pd.to_datetime(weather_df["datetime"])

weather_df.head()

             datetime  temperature  wind_speed  rain  precipitation
0 2025-09-20 00:00:00         25.8         0.3   0.0            0.0
1 2025-09-20 01:00:00         25.7         4.4   0.0            0.0
2 2025-09-20 02:00:00         25.0         6.6   0.0            0.0
3 2025-09-20 03:00:00         23.8         8.9   0.0            0.0
4 2025-09-20 04:00:00         22.6         6.4   0.0            0.0

In [101]:
taxi_trips_with_weather = taxi_trips.merge(weather_df,left_on="datetime_for_weather", right_on="datetime")

In [102]:
taxi_trips_with_weather.head()

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area_id,dropoff_community_area_id,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_centroid_latitude,dropoff_centroid_longitude,datetime_for_weather,trip_start_date,datetime,temperature,wind_speed,rain,precipitation
0,a28e656e3ccb41a818668ad308445c3f69ec29d7,1344830e881c7eba092d0c19fc0d33fb004fce69324141...,2025-09-20 23:45:00,2025-09-21T00:45:00.000,3407,17.65,35,77,47.75,0,0,1,48.75,Cash,Flash Cab,41.835117986,-87.618677767,41.9867118,-87.663416405,2025-09-20 23:00:00,2025-09-20,2025-09-20 23:00:00,22.0,5.2,0.3,0.3
1,a70c202c230b2c3a8aa50da2867486ca20a07deb,137a3605d33badaf4f3ced9115d44ebd822c90ec3cedcb...,2025-09-20 23:45:00,2025-09-21T00:00:00.000,747,2.51,6,8,13.83,0,0,0,14.33,Mobile,Flash Cab,41.944226601,-87.655998182,41.899602111,-87.633308037,2025-09-20 23:00:00,2025-09-20,2025-09-20 23:00:00,22.0,5.2,0.3,0.3
2,a8143c6a22103381d830b2c40783c79c5d7e91c7,449fa4909552757130d09d98ebc7770e2dd94579036b0e...,2025-09-20 23:45:00,2025-09-21T00:00:00.000,372,1.14,24,24,9.5,2.2,0,0,12.2,Mobile,Flash Cab,41.901206994,-87.676355989,41.901206994,-87.676355989,2025-09-20 23:00:00,2025-09-20,2025-09-20 23:00:00,22.0,5.2,0.3,0.3
3,a8e2d3ce2b322e88330f0f7bb3ba14e5fe47e4a3,c3c7eca7dbd2a69ff3195e717334343ed19de792129c84...,2025-09-20 23:45:00,2025-09-20T23:45:00.000,504,2.16,32,8,33.5,0,0,0,34,Credit Card,Globe Taxi,41.878865584,-87.625192142,41.899602111,-87.633308037,2025-09-20 23:00:00,2025-09-20,2025-09-20 23:00:00,22.0,5.2,0.3,0.3
4,ad7a23208bdfdba65c04cb69959a478cd473731d,0bea3de3c36237d68b009b24ee3db86c78e9e618a73a3b...,2025-09-20 23:45:00,2025-09-21T00:15:00.000,1920,14.4,56,6,37.25,0,0,10,47.25,No Charge,Transit Administrative Center Inc,41.79259236,-87.769615453,41.944226601,-87.655998182,2025-09-20 23:00:00,2025-09-20,2025-09-20 23:00:00,22.0,5.2,0.3,0.3

## Adattípusok átalakítása

In [103]:
# Jelenleg majdnem minden string --> nehezebb kezelni a különböző jellegű adatokat

taxi_trips.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17103 entries, 0 to 18540
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   trip_id                     17103 non-null  object
 1   taxi_id                     17103 non-null  object
 2   trip_start_timestamp        17103 non-null  datetime64[ns]
 3   trip_end_timestamp          17103 non-null  object
 4   trip_seconds                17103 non-null  object
 5   trip_miles                  17103 non-null  object
 6   pickup_community_area_id    17103 non-null  object
 7   dropoff_community_area_id   17103 non-null  object
 8   fare                        17103 non-null  object
 9   tips                        17103 non-null  object
 10  tolls                       17103 non-null  object
 11  extras                      17103 non-null  object
 12  trip_total                  17103 non-null  object
 13  payment_type                17103 non-null  object
 14  company                     17103 non-null  object
 15  pickup_centroid_latitude    17103 non-null  object
 16  pickup_centroid_longitude   17103 non-null  object
 17  dropoff_centroid_latitude   17103 non-null  object
 18  dropoff_centroid_longitude  17103 non-null  object
 19  datetime_for_weather        17103 non-null  datetime64[ns]
 20  trip_start_date             17103 non-null  object
dtypes: datetime64[ns](2), object(19)
memory usage: 2.9+ MB

In [104]:
# az eredeti táblát lementjük egy másik változóba azért, hogy később össze lehessen hasonlítani a formázás előtti és utáni állapotot
taxi_trips_original = taxi_trips.copy()

In [105]:
# Adattípusok átírása

data_types = {
    'trip_end_timestamp' : 'datetime64[ns]',
    'trip_seconds' : 'int32',
    'trip_miles' : 'float',
    'pickup_community_area_id' : 'int8',
    'dropoff_community_area_id' : 'int8',
    'fare' : 'float',
    'tips' : 'float',
    'tolls' : 'float',
    'extras' : 'float',
    'trip_total' : 'float',
    'pickup_centroid_latitude' : 'float',
    'pickup_centroid_longitude' : 'float',
    'dropoff_centroid_latitude' : 'float',
    'dropoff_centroid_longitude' : 'float',
}

taxi_trips = taxi_trips.astype(data_types)

In [106]:
taxi_trips.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17103 entries, 0 to 18540
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   trip_id                     17103 non-null  object
 1   taxi_id                     17103 non-null  object
 2   trip_start_timestamp        17103 non-null  datetime64[ns]
 3   trip_end_timestamp          17103 non-null  datetime64[ns]
 4   trip_seconds                17103 non-null  int32
 5   trip_miles                  17103 non-null  float64
 6   pickup_community_area_id    17103 non-null  int8
 7   dropoff_community_area_id   17103 non-null  int8
 8   fare                        17103 non-null  float64
 9   tips                        17103 non-null  float64
 10  tolls                       17103 non-null  float64
 11  extras                      17103 non-null  float64
 12  trip_total                  17103 non-null  float64
 13  payment_type                17103 non-null  object
 14  company                     17103 non-null  object
 15  pickup_centroid_latitude    17103 non-null  float64
 16  pickup_centroid_longitude   17103 non-null  float64
 17  dropoff_centroid_latitude   17103 non-null  float64
 18  dropoff_centroid_longitude  17103 non-null  float64
 19  datetime_for_weather        17103 non-null  datetime64[ns]
 20  trip_start_date             17103 non-null  object
dtypes: datetime64[ns](3), float64(10), int32(1), int8(2), object(5)
memory usage: 2.6+ MB

In [107]:
taxi_trips.describe()

,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area_id,dropoff_community_area_id,fare,tips,tolls,extras,trip_total,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_centroid_latitude,dropoff_centroid_longitude,datetime_for_weather
count,17103,17103,17103.000000,17103.000000,17103.000000,17103.000000,17103.000000,17103.000000,17103.000000,17103.000000,17103.000000,17103.000000,17103.000000,17103.000000,17103.000000,17103
mean,2025-09-20 14:41:37.719698176,2025-09-20 14:59:35.951587328,1078.382681,5.401615,28.959832,24.986435,20.061494,2.014575,0.009421,1.063317,23.453900,41.894118,-87.672453,41.889970,-87.655570,2025-09-20 14:19:13.692334592
min,2025-09-20 00:00:00,2025-09-20 00:00:00,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,41.660136,-87.913625,41.660136,-87.913625,2025-09-20 00:00:00
25%,2025-09-20 11:30:00,2025-09-20 11:45:00,480.000000,1.170000,8.000000,8.000000,8.500000,0.000000,0.000000,0.000000,10.500000,41.877406,-87.663518,41.874005,-87.657233,2025-09-20 11:00:00
50%,2025-09-20 15:00:00,2025-09-20 15:30:00,836.000000,2.580000,28.000000,27.000000,13.600000,0.000000,0.000000,0.000000,15.500000,41.892508,-87.633308,41.892042,-87.633308,2025-09-20 15:00:00
75%,2025-09-20 18:30:00,2025-09-20 18:45:00,1380.000000,8.900000,33.000000,32.000000,29.000000,3.000000,0.000000,1.000000,30.100000,41.922686,-87.623367,41.907520,-87.622173,2025-09-20 18:00:00
max,2025-09-20 23:45:00,2025-09-21 18:15:00,69641.000000,105.750000,77.000000,77.000000,2050.000000,56.750000,12.000000,200.000000,2050.000000,42.009623,-87.534903,42.009623,-87.534903,2025-09-20 23:00:00
std,NaN,NaN,1414.963874,6.022406,23.376017,19.942513,22.323184,3.564835,0.207325,3.950781,24.656527,0.058915,0.091103,0.055554,0.064127,NaN

#### Memória használat változása a korábbi és a mostani átalakított df-el

In [108]:
orig_mem = taxi_trips_original.memory_usage(deep=True).sum()
opt_mem = taxi_trips.memory_usage(deep=True).sum()

reduction = (orig_mem - opt_mem) / orig_mem * 100

print(f'Original: {orig_mem:,} bytes')
print(f'Optimized: {opt_mem:,} bytes')
print(f'Memory reduced by: {reduction:.2f}%')

Original: 21,098,819 bytes
Optimized: 9,363,539 bytes
Memory reduced by: 55.62%

## Sanity checks

In [109]:
# A maximum végidő (lásd describe rész) nagyon magas --> érdemes ránézni

taxi_trips[taxi_trips['trip_end_timestamp'] == taxi_trips['trip_end_timestamp'].max()]

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area_id,dropoff_community_area_id,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_centroid_latitude,dropoff_centroid_longitude,datetime_for_weather,trip_start_date
137,2e9182d33d1c0200820b14a5bc19691a40828b16,4df2912dd50d4f329ca8bbdc29820405a25dab85dd7524...,2025-09-20 23:30:00,2025-09-21 18:15:00,67322,0.37,32,76,4.5,0.0,0.0,0.0,4.5,Cash,Blue Ribbon Taxi Association,41.877406,-87.621972,41.979071,-87.90304,2025-09-20 23:00:00,2025-09-20

In [110]:
# A maximum utazási idő is (lásd describe rész) nagyon magas --> érdemes ránézni
taxi_trips[taxi_trips['trip_seconds'] == taxi_trips['trip_seconds'].max()]

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area_id,dropoff_community_area_id,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_centroid_latitude,dropoff_centroid_longitude,datetime_for_weather,trip_start_date
2017,32cb047ebe8abf2a9eb29ecec11ea18056121c30,55e53aceec1519445bae3e8414b4cbf11e59e50800f714...,2025-09-20 21:15:00,2025-09-21 16:30:00,69641,0.0,24,76,3.25,0.0,0.0,0.0,3.25,Cash,Blue Ribbon Taxi Association,41.901207,-87.676356,41.980264,-87.913625,2025-09-20 21:00:00,2025-09-20

In [111]:
# A maximum fare is (lásd describe rész) nagyon magas --> érdemes ránézni
taxi_trips[taxi_trips['fare'] == taxi_trips['fare'].max()]

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area_id,dropoff_community_area_id,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_centroid_latitude,dropoff_centroid_longitude,datetime_for_weather,trip_start_date
17719,3cd5ea7d397dedb4b291c674a9e55ba462f14ab7,46c4778c3a32454511f96752c509c608955e293da45dbf...,2025-09-20 03:30:00,2025-09-20 03:45:00,966,0.0,29,8,2050.0,0.0,0.0,0.0,2050.0,Cash,Tac - Yellow Cab Association,41.86019,-87.71722,41.899602,-87.633308,2025-09-20 03:00:00,2025-09-20

# Making dimension tables

## Payment type dimension

In [112]:
#Szám ID-t párosítunk a fizetési módok mellé

dim_payment_type = taxi_trips['payment_type'].drop_duplicates().reset_index(drop=True)

#Majd létrehozzuk a df-et hozzá

dim_payment_type = pd.DataFrame(

    {
        "payment_type_id" : range(1,len(dim_payment_type)+1),
        "payment_type": dim_payment_type
    }
)

# A kész df

dim_payment_type

   payment_type_id payment_type
0                1         Cash
1                2       Mobile
2                3  Credit Card
3                4    No Charge
4                5       Prcard
5                6      Unknown
6                7      Dispute

## Company dimension

In [113]:
#Szám ID-t párosítunk a cégek mellé

dim_company = taxi_trips['company'].drop_duplicates().reset_index(drop=True)

#Majd létrehozzuk a df-et hozzá

dim_company = pd.DataFrame(

    {
        "company_id" : range(1,len(dim_company)+1),
        "company": dim_company
    }
)

# A kész df

dim_company

    company_id                               company
0            1                             Flash Cab
1            2                            Globe Taxi
2            3     Transit Administrative Center Inc
3            4          Taxicab Insurance Agency Llc
4            5                  Chicago Independents
5            6                           5 Star Taxi
6            7                          City Service
7            8           Choice Taxi Association Inc
8            9                               Top Cab
9           10                              Sun Taxi
10          11         Taxicab Insurance Agency  LLC
11          12          Tac - Yellow Cab Association
12          13          Blue Ribbon Taxi Association
13          14                      Medallion Leasin
14          15            Tac - Checker Cab Dispatch
15          16                           Wolley Taxi
16          17                       Chicago Taxicab
17          18        Tac - American United Dispatch
18          19         Chicago City Taxi Association
19          20        Star North Taxi Management Llc
20          21          4053 - 40193 Adwar H. Nikola
21          22         312 Medallion Management Corp
22          23  Patriot Taxi Dba Peace Taxi Associat
23          24           Tac - Blue Diamond Dispatch
24          25                            Setare Inc
25          26            5167 - 71969 5167 Taxi Inc
26          27                 Koam Taxi Association
27          28                Tac - Yellow Non Color
28          29               2733 - 74600 Benny Jona

## Merging back to the Fact table

In [114]:
# Visszaírjuk az ID-kat az eredeti taxi_trips táblába

fact_taxi_trips = taxi_trips.merge(dim_payment_type, on='payment_type')
fact_taxi_trips = fact_taxi_trips.merge(dim_company, on='company')

In [115]:
fact_taxi_trips.sample(5)

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area_id,dropoff_community_area_id,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_centroid_latitude,dropoff_centroid_longitude,datetime_for_weather,trip_start_date,payment_type_id,company_id
3477,4bb23cd473fe3c8090bd2ad936e597bb011ad2fb,cf676de36353be7581fc132e7b707e919d1541b82e2d97...,2025-09-20 19:15:00,2025-09-20 19:30:00,420,0.00,8,32,15.00,3.10,0.0,0.0,18.10,Credit Card,Transit Administrative Center Inc,41.890922,-87.618868,41.877406,-87.621972,2025-09-20 19:00:00,2025-09-20,3,3
16284,506b3c37c0260ffc52c10fa988541fcde15edd95,3d90e25b8ab0de4b8255efb250b64017386e76574210ea...,2025-09-20 04:45:00,2025-09-20 05:15:00,1302,17.78,3,44,49.17,0.00,0.0,0.0,49.17,Cash,Flash Cab,41.965812,-87.655879,41.740206,-87.615970,2025-09-20 04:00:00,2025-09-20,1,1
2980,70a5238a3cc465a373be1a9147ec55bb38323593,f72fedda1dcbb0853cc4a2dc803d8bb0348f79cdc08b8a...,2025-09-20 19:45:00,2025-09-20 20:00:00,1085,3.72,6,8,13.10,1.88,0.0,0.0,15.48,Mobile,5 Star Taxi,41.944227,-87.655998,41.899602,-87.633308,2025-09-20 19:00:00,2025-09-20,2,6
7474,762562a54438df3e9cdecd9b11fa5955c88ec143,05e98fcdd5101fb75c828458c6af3370de5f0ffcf07892...,2025-09-20 16:00:00,2025-09-20 16:00:00,0,0.00,69,69,3.25,0.00,0.0,0.0,3.25,No Charge,Transit Administrative Center Inc,41.763247,-87.616134,41.763247,-87.616134,2025-09-20 16:00:00,2025-09-20,4,3
10644,f5b2ae1467016e0f9725ae6de2168e889f11c13e,553184281bcc7d9fe71f9a228310defd345589d61b771b...,2025-09-20 13:15:00,2025-09-20 14:15:00,2954,18.17,32,76,46.00,10.10,0.0,4.0,60.60,Credit Card,Choice Taxi Association Inc,41.884987,-87.620993,41.979071,-87.903040,2025-09-20 13:00:00,2025-09-20,3,8

In [116]:
# Az ID-knak megfelelő eredeti szöveges értékes oszlopok droppolása

fact_taxi_trips.drop(['payment_type','company'], axis=1, inplace=True)

In [117]:
fact_taxi_trips.sample(5)

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area_id,dropoff_community_area_id,fare,tips,tolls,extras,trip_total,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_centroid_latitude,dropoff_centroid_longitude,datetime_for_weather,trip_start_date,payment_type_id,company_id
8368,3ca39f111435496e0a55e575e58aa037078d183d,64375e2b26ec87f4da6e0c3b8887d949b8e91e9072a428...,2025-09-20 15:15:00,2025-09-20 15:15:00,240,0.90,32,8,5.50,4.00,0.0,1.0,10.50,41.884987,-87.620993,41.891972,-87.612945,2025-09-20 15:00:00,2025-09-20,3,3
2691,53f00b4b9287c228afb418c958ef8c4dfc5ab5f3,e637e1afe0dab0e2d04c635335602caf1045d43e3741c2...,2025-09-20 20:00:00,2025-09-20 20:15:00,720,1.30,7,8,9.30,0.00,0.0,0.0,9.30,41.922686,-87.649489,41.899602,-87.633308,2025-09-20 20:00:00,2025-09-20,3,3
10858,4bd22a76dc9dc4b3dacefd77c413ac0fa51ae4de,4903c88e6b8e413fd55b8680ee639b42aca85ade05fb30...,2025-09-20 13:15:00,2025-09-20 13:15:00,480,0.80,8,8,6.50,0.00,0.0,1.0,7.50,41.899156,-87.626211,41.892508,-87.626215,2025-09-20 13:00:00,2025-09-20,1,3
9702,fc8ea62759787c80575364b8edd17808331c0788,96c3fa383c9adacc965af778248d6ef1b3a20ada7e623e...,2025-09-20 14:00:00,2025-09-20 14:30:00,1560,7.05,8,29,25.79,0.00,0.0,0.0,26.29,41.895033,-87.619711,41.860762,-87.700692,2025-09-20 14:00:00,2025-09-20,2,1
6068,12a3dc1448e334be3f12b6f14fe8003db611a8ad,aefac4ce6d1a787e28b51b047402bdf876c2b3473e39c9...,2025-09-20 17:15:00,2025-09-20 17:30:00,1234,2.72,33,32,25.75,8.81,0.0,9.0,44.06,41.849247,-87.624135,41.884987,-87.620993,2025-09-20 17:00:00,2025-09-20,3,4

In [119]:
dim_payment_type.to_csv('dim_payment_type.csv',index=False)
dim_company.to_csv('dim_company.csv',index=False)

## Create update logic for Dimension tables

In [127]:
dim_payment_type = taxi_trips['payment_type'].drop_duplicates().reset_index(drop=True)

#Majd létrehozzuk a df-et hozzá

dim_payment_type = pd.DataFrame(

    {
        "payment_type_id" : range(1,len(dim_payment_type)+1),
        "payment_type": dim_payment_type
    }
)


# dummy df generálása (mintha a holnapi adatok lennének) --> a kód felkészítése a folyamatos update-re, új adatokra

dummy_payment_type_data = [

{'payment_type': 'Credit Card'},
{'payment_type': 'X'},
{'payment_type': 'Y'},
{'payment_type': 'X'},

]

dummy_payment_type_data_df = pd.DataFrame(dummy_payment_type_data)

#duplikációk eltávolítása

todays_payment_types = pd.DataFrame(dummy_payment_type_data_df['payment_type'].unique(), columns=['payment_type'])

#majd kiadatjuk az összes olyan értéket a dummy táblából ami a korábban definiált dim táblában nincs benne

new_payment_types = todays_payment_types[~todays_payment_types['payment_type'].isin(dim_payment_type['payment_type'])]

#majd azért, hogy ne a dimenzió táblában lévő számnál lévő értéket írja felül, hanem adjon hozzá egy új ID-t, ezért szükséges az alábbi

if not new_payment_types.empty:
    max_id = dim_payment_type['payment_type_id'].max()
    new_payment_types['payment_type_id'] = range(max_id+1,max_id+1+len(new_payment_types))
    dim_payment_type = pd.concat([dim_payment_type, new_payment_types], ignore_index = True )

dim_payment_type

C:\Users\Adam\AppData\Local\Temp\ipykernel_15288\3383357295.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_payment_types['payment_type_id'] = range(max_id+1,max_id+1+len(new_payment_types))

   payment_type_id payment_type
0                1         Cash
1                2       Mobile
2                3  Credit Card
3                4    No Charge
4                5       Prcard
5                6      Unknown
6                7      Dispute
7                8            X
8                9            Y

In [128]:
dim_company = taxi_trips['company'].drop_duplicates().reset_index(drop=True)

#Majd létrehozzuk a df-et hozzá

dim_company = pd.DataFrame(

    {
        "company_id" : range(1,len(dim_company)+1),
        "company": dim_company
    }
)


# dummy df generálása (mintha a holnapi adatok lennének) --> a kód felkészítése a folyamatos update-re, új adatokra

dummy_company_data = [

{'company': 'Metro Jet Taxi A'},
{'company': 'X'},
{'company': 'Y'},
{'company': 'X'},

]

dummy_company_data_df = pd.DataFrame(dummy_company_data)

#duplikációk eltávolítása

todays_companies = pd.DataFrame(dummy_company_data_df['company'].unique(), columns=['company'])

#majd kiadatjuk az összes olyan értéket a dummy táblából ami a korábban definiált dim táblában nincs benne

new_companies = todays_companies[~todays_companies['company'].isin(dim_company['company'])]

#majd azért, hogy ne a dimenzió táblában lévő számnál lévő értéket írja felül, hanem adjon hozzá egy új ID-t, ezért szükséges az alábbi

if not new_companies.empty:
    max_id = dim_company['company_id'].max()
    new_companies['company_id'] = range(max_id+1,max_id+1+len(new_companies))
    dim_company = pd.concat([dim_company, new_companies], ignore_index = True )

dim_company

    company_id                               company
0            1                             Flash Cab
1            2                            Globe Taxi
2            3     Transit Administrative Center Inc
3            4          Taxicab Insurance Agency Llc
4            5                  Chicago Independents
5            6                           5 Star Taxi
6            7                          City Service
7            8           Choice Taxi Association Inc
8            9                               Top Cab
9           10                              Sun Taxi
10          11         Taxicab Insurance Agency  LLC
11          12          Tac - Yellow Cab Association
12          13          Blue Ribbon Taxi Association
13          14                      Medallion Leasin
14          15            Tac - Checker Cab Dispatch
15          16                           Wolley Taxi
16          17                       Chicago Taxicab
17          18        Tac - American United Dispatch
18          19         Chicago City Taxi Association
19          20        Star North Taxi Management Llc
20          21          4053 - 40193 Adwar H. Nikola
21          22         312 Medallion Management Corp
22          23  Patriot Taxi Dba Peace Taxi Associat
23          24           Tac - Blue Diamond Dispatch
24          25                            Setare Inc
25          26            5167 - 71969 5167 Taxi Inc
26          27                 Koam Taxi Association
27          28                Tac - Yellow Non Color
28          29               2733 - 74600 Benny Jona
29          30                      Metro Jet Taxi A
30          31                                     X
31          32                                     Y